# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Parinya Luangchaisuk
  description: Configure firewall security and open ports using firewalld
  company: Personal
  license: MIT-0
  min_ansible_version: '2.11'

  platforms:
    - name: Fedora
      versions:
        - "39"
        - "40"
        - "41"
    - name: EL
      versions:
        - "9"
        - "10"

  galaxy_tags:
    - security
    - firewall
    - firewalld
    - ssh
    - networking

dependencies:
  - role: common
