---
galaxy_info:
  role_name: gnome
  author: Parinya
  description: GNOME Desktop Settings configuration via dconf
  company: none
  license: MIT
  min_ansible_version: "2.11"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - desktop

dependencies: []
