# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Parinya Luangchaisuk
  description: >-
    Configure GNOME-based desktop environment with essential
    applications and tools
  company: Personal
  license: MIT-0
  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - desktop
    - gnome
    - fedora
    - flatpak
    - starship

dependencies:
  - role: common
    vars:
      ensure_base_packages: true
