---
# SPDX-License-Identifier: MIT-0
- name: Check if VSCode repository exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/vscode.repo
  register: desktop_vscode_repo

- name: Add VSCode repository
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: "{{ desktop_vscode_repo_baseurl }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ desktop_vscode_gpg_key_url }}"
  when: not desktop_vscode_repo.stat.exists

- name: Install Visual Studio Code
  ansible.builtin.dnf:
    name: code
    state: present

- name: Ensure VS Code User Directory Exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/Code/User"
    state: directory
    mode: "0755"

- name: Check if VS Code settings file exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/roles/desktop/files/vscode/settings.json"
  register: desktop_vscode_settings_stat
  ignore_errors: true

- name: Copy VS Code Settings if file exists
  ansible.builtin.copy:
    src: vscode/settings.json
    dest: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
    mode: "0644"
    backup: true
  when: desktop_vscode_settings_stat.stat.exists
