---
# SPDX-License-Identifier: MIT-0
# Default variables for font role

# Feature toggle
font_install_enabled: true

# Font packages to install
font_packages:
  - jetbrains-mono-fonts
  - fira-code-fonts
  - inter-fonts

# COPR repository for JetBrains Mono fonts
font_jetbrains_copr_repo: elxreno/jetbrains-mono-fonts

# COPR repository for Inter fonts
font_inter_copr_repo: burhanverse/inter-fonts
