---
# SPDX-License-Identifier: MIT-0
# Wi-Fi configuration role main entry point
# This role configures Wi-Fi power management settings for optimal performance

- name: Include unblock tasks
  ansible.builtin.include_tasks: unblock.yml
  when: wifi_task == "unblock"
  tags:
    - wifi
    - unblock

- name: Disable Wi-Fi power save
  ansible.builtin.import_tasks: no_powersave.yml
  tags:
    - wifi

- name: Configure GRUB for Wi-Fi power management
  ansible.builtin.import_tasks: grub.yml
  tags:
    - wifi

- name: Disable unnecessary services
  ansible.builtin.import_tasks: disable_services.yml
  tags:
    - wifi
