# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/security

- name: Configure firewalld
  ansible.builtin.import_tasks: firewalld.yml
  tags:
    - security
    - firewall

- name: Configure SSH port
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - security
    - ssh
    - firewall

- name: Configure custom ports
  ansible.builtin.import_tasks: custom-ports.yml
  when: security_custom_ports | length > 0
  tags:
    - security
    - firewall
    - custom-ports
