# SPDX-License-Identifier: MIT-0
---
# handlers file for roles/embed

- name: Trigger udev rules reload for serial devices
  ansible.builtin.command: udevadm control --reload-rules
  become: true
  changed_when: false
  listen: embed reload udev

- name: Trigger udev trigger for serial devices
  ansible.builtin.command: udevadm trigger
  become: true
  changed_when: false
  listen: embed trigger udev
