#SPDX-License-Identifier: MIT-0
---
# vars file for roles/desktop
# These are high-priority variables used internally by the role

# Visual Studio Code repository configuration
vscode_repo_name: code
vscode_repo_description: Visual Studio Code

# Starship binary path
starship_bin_path: /usr/local/bin/starship

