# SPDX-License-Identifier: MIT-0
---
# defaults file for roles/desktop
# These are low-priority variables that can be overridden by playbooks or host variables

# Feature flags for conditional role execution
desktop_install_desktop_packages: true
desktop_install_vscode: true
desktop_install_starship: true
desktop_install_flatpak_apps: true
desktop_install_flatpak: true
desktop_enable_flatpak_user: true
desktop_install_gnome_extensions: true
desktop_install_zed: true

# GNOME extensions
desktop_gnome_extensions:
  - gnome-shell-extension-pop-shell
  - nautilus-python

# Zed editor download URL
desktop_zed_download_url: "https://github.com/zed-industries/zed/releases/latest/download/zed-linux-x86_64.tar.gz"

# Brave browser URLs
desktop_brave_repo_url: "https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo"
desktop_brave_gpg_key_url: "https://brave-browser-rpm-release.s3.brave.com/brave-core.asc"

# VSCode URLs
desktop_vscode_gpg_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
desktop_vscode_repo_baseurl: "https://packages.microsoft.com/yumrepos/vscode"

# Flatpak applications to install
desktop_flatpak_apps_list:
  - com.getpostman.Postman
  - org.signal.Signal
  - com.obsproject.Studio
  - net.ankiweb.Anki
  - com.rustdesk.RustDesk
  - it.mijorus.gearlever
  - com.github.micahflee.torbrowser-launcher
  - com.transmissionbt.Transmission
  - org.gimp.GIMP
  - org.kde.krita
  - org.blender.Blender
  - org.inkscape.Inkscape
  - org.gnome.HandyGamer
  - org.gnome.World.PikaBackup
  - org.gnome.Snapshot
  - org.gnome.baobab
  - io.github.celluloid_player.Celluloid
  - com.uploadedlobster.peek
  - org.gnome.design.IconLibrary
  - org.gnome.gitlab.YaLTeR.VideoTrimmer
  - org.gnome.gitlab.jonasschmidtmann.VideoTranscoder
  - org.gnome.gitlab.somas.AmbientNoise
  - com.github.maoschanz.drawing
  - com.rafaelmardojai.Blanket
  - io.github.zen_browser.zen
  - com.jgraph.drawio.desktop
  - org.gnome.Calculator
  - org.gnome.Calendar
  - org.gnome.Clocks
  - org.gnome.Contacts
  - org.gnome.Documents
  - org.gnome.Extensions
  - org.gnome.Epiphany
  - org.gnome.Logs
  - org.gnome.Maps
  - org.gnome.Music
  - org.gnome.Nautilus
  - org.gnome.Photos
  - org.gnome.Rhythmbox3
  - org.gnome.Software
  - org.gnome.TextEditor
  - org.gnome.Weather

# Desktop packages to install
desktop_packages:
  - okular
  - xclip
  - gnome-extensions-app
  - gnome-tweaks

# Starship configuration
desktop_starship_install: true
desktop_starship_config_path: /etc/bashrc

# Installation URLs
desktop_flathub_repo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
desktop_flathub_repo_url_alt: "https://flathub.org/repo/flathub.flatpakrepo"
desktop_starship_install_url: "https://starship.rs/install.sh"
