---
- name: "Apply Settings for {{ section.path }}"
  community.general.dconf:
    key: "{{ section.path }}{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ section['settings'] | dict2items }}"
  loop_control:
    label: "{{ section.path }}{{ item.key }}"
  become: true
  become_user: "{{ ansible_user_id }}"
  ignore_errors: true
