---
- name: "Apply Settings for {{ section.path }}"
  community.general.dconf:
    key: "{{ section.path }}{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ section.values | dict2items }}"
  loop_control:
    label: "{{ section.path }}{{ item.key }}"
