---
# tasks file for gnome

- name: Setup GNOME Dependencies
  ansible.builtin.import_tasks: install.yml
  tags: [gnome, install]

- name: Configure GNOME Settings
  ansible.builtin.import_tasks: configure.yml
  tags: [gnome, configure]
