# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  role_name: font
  author: Parinya Luangchaisuk
  description: Ansible role to install fonts
  company: Personal
  license: MIT-0
  min_ansible_version: '2.11'

  platforms:
    - name: Fedora
      versions:
        - "39"
        - "40"
        - "41"
    - name: EL
      versions:
        - "9"
        - "10"

  galaxy_tags:
    - fonts
    - typography
    - system

dependencies: []
