# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  role_name: font
  author: Parinya Luangchaisuk
  description: Install recommended fonts for Fedora including Thai, Unicode, code, and emoji fonts
  company: Personal
  license: MIT-0
  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - fonts
    - thai
    - unicode
    - coding
    - terminal
    - emoji
    - typography
    - system
    - dnf

dependencies: []
