---
# SPDX-License-Identifier: MIT-0
# Meta information for font role

galaxy_info:
  author: Parinya Luangchaisuk
  description: Install programming fonts (JetBrains Mono and Fira Code)
  company: ""
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - fonts
    - jetbrains
    - firacode
    - development

dependencies: []
